# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Romina Crugo
    description:  Est√©tica y Spa
    keywords:     estetica, spa
    language:     es
    robots:       index, follow

  stylesheets:    [main_blue.css, jquery-ui-1.8.16.custom.css]

  javascripts:    [jquery-1.6.2.min.js, jquery-ui-1.8.16.custom.min.js, jquery.history.js, global-functions.js, jquery.floatobject.js]

  has_layout:     true
  layout:         layout
